package com.example.syncrowbackend.common.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode{
    AUTHENTICATION_FAILED(401, "AUTHENTICATION_FAILED", "AUTHENTICATION FAILED ERROR"),
    USER_NOT_FOUND_ERROR(400, "USER-NOT_FOUND", "USER NOT FOUND ERROR"),
    POST_NOT_FOUND_ERROR(400, "POST-NOT-FOUND", "POST NOT FOUND ERROR"),
    POST_NOT_DELETABLE(400, "POST_NOT_DELETABLE", "POST NOT DELETABLE"),
    GROUP_NOT_FOUND_ERROR(400, "GROUP-NOT-FOUND", "GROUP NOT FOUND ERROR"),
    FRIEND_REQUEST_ROOM_NOT_FOUND_ERROR(400, "FRIEND_REQUEST_ROOM_NOT_FOUND_ERROR", "FRIEND_REQUEST_ROOM NOT FOUND ERROR"),
    PERMISSION_NOT_GRANTED_ERROR(403, "PERMISSION-NOT-GRANTED", "PERMISSION NOT GRANTED ERROR"),
    INTERNAL_SERVER_ERROR(500, "INTERNAL-SERVER-ERROR", "INTERNAL SERVER ERROR"),
    DUPLICATED_FRIEND_REQUEST(400, "DUPLICATED_FRIEND_REQUEST", "DUPLICATED FRIEND REQUEST"),
    FRIEND_REQUEST_NOT_FOUND_ERROR(400, "FRIEND_REQUEST_NOT_FOUND", "FRIEND REQUEST NOT FOUND"),
    FRIEND_REQUEST_ALREADY_REACTED(400, "FRIEND_REQUEST_ALREADY_REACTED", "FRIEND REQUEST ALREADY REACTED"),
    FRIEND_REQUEST_WRONG_USER(400, "FRIEND_REQUEST_WRONG_USER", "FRIEND REQUEST WRONG USER"),
    FRIEND_REACT_WRONG_USER(400, "FRIEND_REACT_WRONG_USER", "FRIEND REACT WRONG USER"),
    NOTIFICATION_NOT_FOUND_ERROR(400, "NOTIFICATION_NOT_FOUND", "NOTIFICATION NOT FOUND ERROR"),
    NOTIFICATION_WRONG_USER(400, "NOTIFICATION_NOT_UPDATABLE", "NOTIFICATION NOT UPDATABLE"),
    METHOD_ARGUMENT_TYPE_MISMATCHED(400, "METHOD_ARGUMENT_TYPE_MISMATCHED", "METHOD ARGUMENT TYPE MISMATCHED");

    private final int status;
    private final String errorType;
    private final String message;
}