package com.example.syncrowbackend.common.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode{
    AUTHENTICATION_FAILED(401, "AUTHENTICATION_FAILED", "AUTHENTICATION FAILED ERROR"),
    USER_NOT_FOUND_ERROR(400, "USER-NOT_FOUND", "USER NOT FOUND ERROR"),
    POST_NOT_FOUND_ERROR(400, "POST-NOT-FOUND", "POST NOT FOUND ERROR"),
    POST_NOT_DELETABLE(400, "POST_NOT_DELETABLE", "POST NOT DELETABLE"),
    GROUP_NOT_FOUND_ERROR(400, "GROUP-NOT-FOUND", "GROUP NOT FOUND ERROR"),
    FRIEND_REQUEST_ROOM_NOT_FOUND_ERROR(400, "FRIEND_REQUEST_ROOM_NOT_FOUND_ERROR", "FRIEND_REQUEST_ROOM NOT FOUND ERROR"),
    PERMISSION_NOT_GRANTED_ERROR(403, "PERMISSION-NOT-GRANTED", "PERMISSION NOT GRANTED ERROR"),
    INTERNAL_SERVER_ERROR(500, "INTERNAL-SERVER-ERROR", "INTERNAL SERVER ERROR"),
    FRIEND_REQUEST_NOT_FOUND_ERROR(400, "FRIEND_REQUEST_NOT_FOUND", "FRIEND REQUEST NOT FOUND"),
    DUPLICATED_FRIEND_REQUEST(400, "DUPLICATED_FRIEND_REQUEST", "DUPLICATED FRIEND REQUEST"),
    ALREADY_REACTED_FRIEND_REQUEST(400, "ALREADY_REACTED_FRIEND_REQUEST", "ALREADY REACTED FRIEND REQUEST"),
    NOTIFICATION_NOT_FOUND_ERROR(400, "NOTIFICATION_NOT_FOUND", "NOTIFICATION NOT FOUND ERROR"),
    METHOD_ARGUMENT_TYPE_MISMATCHED(400, "METHOD_ARGUMENT_TYPE_MISMATCHED", "METHOD ARGUMENT TYPE MISMATCHED"),
    METHOD_NOT_ALLOWED(405, "METHOD_NOT_ALLOWED", "METHOD NOT ALLOWED"),
    PARAMETER_BINDING_ERROR(400, "PARAMETER_BINDING_ERROR", "PARAMETER BINDING ERROR");

    private final int status;
    private final String errorType;
    private final String message;
}